/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Theme.Tema;
import java.awt.Toolkit;

/**
 *
 * @author suporte
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        setIcon();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        btnLogout = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AluCadastro = new javax.swing.JMenuItem();
        GeraMatricula = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuNovoFunc = new javax.swing.JMenu();
        jMenuCadFunc = new javax.swing.JMenuItem();
        jMenuNovoCargo = new javax.swing.JMenu();
        jMenuCadCargo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuNovoCurso = new javax.swing.JMenu();
        jMenuCadCursos = new javax.swing.JMenuItem();
        jMenuNovoDIsc = new javax.swing.JMenu();
        jMenuCadDisc = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuCadMensalidades = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuNovoItem = new javax.swing.JMenu();
        jMenuCadItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logout-32.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/exit-32.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/10889_64x64.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(434, 25));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Aluno_16x16.png"))); // NOI18N
        jMenu1.setText("Aluno");
        jMenu1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/disquete_16x16.png"))); // NOI18N
        jMenu1.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/disquete_16x16.png"))); // NOI18N
        jMenu1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/disquete_16x16.png"))); // NOI18N
        jMenu1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/disquete_16x16.png"))); // NOI18N

        AluCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/disquete_16x16.png"))); // NOI18N
        AluCadastro.setText("Cadastro");
        AluCadastro.setRolloverEnabled(true);
        AluCadastro.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/disquete_16x16.png"))); // NOI18N
        AluCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AluCadastroActionPerformed(evt);
            }
        });
        jMenu1.add(AluCadastro);

        GeraMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/disquete_16x16.png"))); // NOI18N
        GeraMatricula.setText("Gerar Matricula");
        GeraMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeraMatriculaActionPerformed(evt);
            }
        });
        jMenu1.add(GeraMatricula);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Funcionarios_16x16.png"))); // NOI18N
        jMenu2.setText("Funcionário");

        jMenuNovoFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/disquete_16x16.png"))); // NOI18N
        jMenuNovoFunc.setText("Novo");

        jMenuCadFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Capacete_16x16.png"))); // NOI18N
        jMenuCadFunc.setText("Cadastro");
        jMenuCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadFuncActionPerformed(evt);
            }
        });
        jMenuNovoFunc.add(jMenuCadFunc);

        jMenu2.add(jMenuNovoFunc);

        jMenuNovoCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/disquete_16x16.png"))); // NOI18N
        jMenuNovoCargo.setText("Cargo");

        jMenuCadCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/usuario_16x16.png"))); // NOI18N
        jMenuCadCargo.setText("Cadastro");
        jMenuCadCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadCargoActionPerformed(evt);
            }
        });
        jMenuNovoCargo.add(jMenuCadCargo);

        jMenu2.add(jMenuNovoCargo);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/livro_16x16.png"))); // NOI18N
        jMenu3.setText("Cursos");

        jMenuNovoCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/disquete_16x16.png"))); // NOI18N
        jMenuNovoCurso.setText("Novo");

        jMenuCadCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/livro_16x16.png"))); // NOI18N
        jMenuCadCursos.setText("Cadastro");
        jMenuCadCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadCursosActionPerformed(evt);
            }
        });
        jMenuNovoCurso.add(jMenuCadCursos);

        jMenu3.add(jMenuNovoCurso);

        jMenuNovoDIsc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/disquete_16x16.png"))); // NOI18N
        jMenuNovoDIsc.setText("Disciplina");

        jMenuCadDisc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/livro_16x16.png"))); // NOI18N
        jMenuCadDisc.setText("Cadastro");
        jMenuCadDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadDiscActionPerformed(evt);
            }
        });
        jMenuNovoDIsc.add(jMenuCadDisc);

        jMenu3.add(jMenuNovoDIsc);

        jMenu6.setText("Mensalidades");

        jMenuCadMensalidades.setText("Acompanhamento");
        jMenuCadMensalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadMensalidadesActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuCadMensalidades);

        jMenu3.add(jMenu6);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/caixa_16x16.png"))); // NOI18N
        jMenu4.setText("Produtos");

        jMenuNovoItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/disquete_16x16.png"))); // NOI18N
        jMenuNovoItem.setText("Item");

        jMenuCadItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cartao_16x16.png"))); // NOI18N
        jMenuCadItem.setText("Cadastro");
        jMenuCadItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadItemActionPerformed(evt);
            }
        });
        jMenuNovoItem.add(jMenuCadItem);

        jMenu4.add(jMenuNovoItem);

        jMenuItem1.setText("Saldo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/impressora.png"))); // NOI18N
        jMenu5.setText("Relatórios");
        jMenuBar1.add(jMenu5);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/interrogacao.png"))); // NOI18N
        jMenu11.setText("Ajuda");

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/senha.png"))); // NOI18N
        jMenu12.setText("Trocar Senha");
        jMenu11.add(jMenu12);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(btnSair))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AluCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AluCadastroActionPerformed
        CadAluno novo = new CadAluno();
        novo.setVisible(true);
    }//GEN-LAST:event_AluCadastroActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Form_TelaLogin login = new Form_TelaLogin();
        login.setVisible(true);
        FormPrincipal.this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void jMenuCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadFuncActionPerformed
        CadFuncionarios novo = new CadFuncionarios();
        
        novo.setVisible(true);
    }//GEN-LAST:event_jMenuCadFuncActionPerformed

    private void jMenuCadCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadCargoActionPerformed
        CadCargos novo = new CadCargos();
        
        novo.setVisible(true);
        
       
    }//GEN-LAST:event_jMenuCadCargoActionPerformed

    private void jMenuCadCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadCursosActionPerformed
        CadCursos novo = new CadCursos();
        novo.setVisible(true);
    }//GEN-LAST:event_jMenuCadCursosActionPerformed

    private void jMenuCadDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadDiscActionPerformed
        CadDisciplinas novo = new CadDisciplinas();
        novo.setVisible(true);
    }//GEN-LAST:event_jMenuCadDiscActionPerformed

    private void jMenuCadItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadItemActionPerformed
        CadItens novo = new CadItens();
        novo.setVisible(true);
    }//GEN-LAST:event_jMenuCadItemActionPerformed

    private void GeraMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeraMatriculaActionPerformed
        CadMatriculas novo = new CadMatriculas();
        novo.setVisible(true);
    }//GEN-LAST:event_GeraMatriculaActionPerformed

    private void jMenuCadMensalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadMensalidadesActionPerformed
       CadMensalidades novo = new CadMensalidades();
       novo.setVisible(true);
    }//GEN-LAST:event_jMenuCadMensalidadesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       CadSAldos saldo = new CadSAldos();
       saldo.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormVendas venda = new FormVendas();
        venda.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tema.Tema();
                new FormPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AluCadastro;
    private javax.swing.JMenuItem GeraMatricula;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadCargo;
    private javax.swing.JMenuItem jMenuCadCursos;
    private javax.swing.JMenuItem jMenuCadDisc;
    private javax.swing.JMenuItem jMenuCadFunc;
    private javax.swing.JMenuItem jMenuCadItem;
    private javax.swing.JMenuItem jMenuCadMensalidades;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu jMenuNovoCargo;
    private javax.swing.JMenu jMenuNovoCurso;
    private javax.swing.JMenu jMenuNovoDIsc;
    private javax.swing.JMenu jMenuNovoFunc;
    private javax.swing.JMenu jMenuNovoItem;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/pc.png")));
    }

}
