/**
 * Generated by Gas3 v3.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package Daos {

    [Bindable]
    [RemoteClass(alias="Daos.DaoAluno")]
    public class DaoAluno extends DaoAlunoBase {

        public function DaoAluno() {
            super();
        }
    }
}