/**
 * Generated by Gas3 v3.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (DaoAluno.as).
 */

package Daos {

    import Classes.Alunos;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class DaoAlunoBase extends Alunos {

        public function DaoAlunoBase() {
            super();
        }


        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
        }
    }
}