/**
 * Generated by Gas3 v3.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package Messages {

    [Bindable]
    [RemoteClass(alias="Messages.Cmessage")]
    public class Cmessage extends CmessageBase {

        public function Cmessage() {
            super();
        }
    }
}