/**
 * Generated by Gas3 v3.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Alunos.as).
 */

package Classes {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class AlunosBase extends Pessoa {

        public function AlunosBase() {
            super();
        }

        protected var _matricula:int;

        public function set matricula(value:int):void {
            _matricula = value;
        }
        public function get matricula():int {
            return _matricula;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _matricula = input.readObject() as int;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_matricula);
        }
    }
}