/**
 * Generated by Gas3 v3.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Cursos.as).
 */

package Classes {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class CursosBase implements IExternalizable {

        public function CursosBase() {
        }

        public var _descricao:String;
        public var _status:String;
        public var _valor:Number;

        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }

        public function set status(value:String):void {
            _status = value;
        }
        public function get status():String {
            return _status;
        }

        public function set valor(value:Number):void {
            _valor = value;
        }
        public function get valor():Number {
            return _valor;
        }

        public function readExternal(input:IDataInput):void {
            _descricao = input.readObject() as String;
            _status = input.readObject() as String;
            _valor = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_descricao);
            output.writeObject(_status);
            output.writeObject(_valor);
        }
    }
}