/**
 * Generated by Gas3 v3.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package Classes {

    [Bindable]
    [RemoteClass(alias="Classes.Cursos")]
    public class Cursos extends CursosBase {

        public function Cursos() {
            super();
        }
    }
}