/**
 * Generated by Gas3 v3.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Matriculas.as).
 */

package Classes {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class MatriculasBase implements IExternalizable {

        public function MatriculasBase() {
        }

        public var _aluno:int;
        public var _codigo:int;
        public var _dataMatricula:Date;
        public var _usuario:int;

        public function set aluno(value:int):void {
            _aluno = value;
        }
        public function get aluno():int {
            return _aluno;
        }

        public function set codigo(value:int):void {
            _codigo = value;
        }
        public function get codigo():int {
            return _codigo;
        }

        public function set dataMatricula(value:Date):void {
            _dataMatricula = value;
        }
        public function get dataMatricula():Date {
            return _dataMatricula;
        }

        public function set usuario(value:int):void {
            _usuario = value;
        }
        public function get usuario():int {
            return _usuario;
        }

        public function readExternal(input:IDataInput):void {
            _aluno = input.readObject() as int;
            _codigo = input.readObject() as int;
            _dataMatricula = input.readObject() as Date;
            _usuario = input.readObject() as int;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_aluno);
            output.writeObject(_codigo);
            output.writeObject(_dataMatricula);
            output.writeObject(_usuario);
        }
    }
}