/**
 * Generated by Gas3 v3.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Pessoa.as).
 */

package Classes {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class PessoaBase implements IExternalizable {

        public function PessoaBase() {
        }

        protected var _bairro:String;
        protected var _celular:String;
        protected var _cep:String;
        protected var _cidade:String;
        protected var _codigo:int;
        protected var _cpf:String;
        protected var _dataNascimento:Date;
        protected var _email:String;
        protected var _endereco:String;
        protected var _nome:String;
        protected var _numero:int;
        protected var _rg:String;
        protected var _status:String;
        protected var _telefone:String;
        protected var _uf:String;

        public function set bairro(value:String):void {
            _bairro = value;
        }
        public function get bairro():String {
            return _bairro;
        }

        public function set celular(value:String):void {
            _celular = value;
        }
        public function get celular():String {
            return _celular;
        }

        public function set cep(value:String):void {
            _cep = value;
        }
        public function get cep():String {
            return _cep;
        }

        public function set cidade(value:String):void {
            _cidade = value;
        }
        public function get cidade():String {
            return _cidade;
        }

        public function set codigo(value:int):void {
            _codigo = value;
        }
        public function get codigo():int {
            return _codigo;
        }

        public function set cpf(value:String):void {
            _cpf = value;
        }
        public function get cpf():String {
            return _cpf;
        }

        public function set dataNascimento(value:Date):void {
            _dataNascimento = value;
        }
        public function get dataNascimento():Date {
            return _dataNascimento;
        }

        public function set email(value:String):void {
            _email = value;
        }
        public function get email():String {
            return _email;
        }

        public function set endereco(value:String):void {
            _endereco = value;
        }
        public function get endereco():String {
            return _endereco;
        }

        public function set nome(value:String):void {
            _nome = value;
        }
        public function get nome():String {
            return _nome;
        }

        public function set numero(value:int):void {
            _numero = value;
        }
        public function get numero():int {
            return _numero;
        }

        public function set rg(value:String):void {
            _rg = value;
        }
        public function get rg():String {
            return _rg;
        }

        public function set status(value:String):void {
            _status = value;
        }
        public function get status():String {
            return _status;
        }

        public function set telefone(value:String):void {
            _telefone = value;
        }
        public function get telefone():String {
            return _telefone;
        }

        public function set uf(value:String):void {
            _uf = value;
        }
        public function get uf():String {
            return _uf;
        }

        public function readExternal(input:IDataInput):void {
            _bairro = input.readObject() as String;
            _celular = input.readObject() as String;
            _cep = input.readObject() as String;
            _cidade = input.readObject() as String;
            _codigo = input.readObject() as int;
            _cpf = input.readObject() as String;
            _dataNascimento = input.readObject() as Date;
            _email = input.readObject() as String;
            _endereco = input.readObject() as String;
            _nome = input.readObject() as String;
            _numero = input.readObject() as int;
            _rg = input.readObject() as String;
            _status = input.readObject() as String;
            _telefone = input.readObject() as String;
            _uf = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_bairro);
            output.writeObject(_celular);
            output.writeObject(_cep);
            output.writeObject(_cidade);
            output.writeObject(_codigo);
            output.writeObject(_cpf);
            output.writeObject(_dataNascimento);
            output.writeObject(_email);
            output.writeObject(_endereco);
            output.writeObject(_nome);
            output.writeObject(_numero);
            output.writeObject(_rg);
            output.writeObject(_status);
            output.writeObject(_telefone);
            output.writeObject(_uf);
        }
    }
}