/**
 * Generated by Gas3 v3.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (SaldoItem.as).
 */

package Classes {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class SaldoItemBase extends Itens {

        public function SaldoItemBase() {
            super();
        }

        public var _dataAtualizada:Date;
        public var _saldo:int;

        public function set dataAtualizada(value:Date):void {
            _dataAtualizada = value;
        }
        public function get dataAtualizada():Date {
            return _dataAtualizada;
        }

        public function set saldo(value:int):void {
            _saldo = value;
        }
        public function get saldo():int {
            return _saldo;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _dataAtualizada = input.readObject() as Date;
            _saldo = input.readObject() as int;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_dataAtualizada);
            output.writeObject(_saldo);
        }
    }
}