/**
 * Generated by Gas3 v3.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Usuarios.as).
 */

package Classes {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class UsuariosBase extends Funcionarios {

        public function UsuariosBase() {
            super();
        }

        public var _login:String;
        public var _senha:String;

        public function set login(value:String):void {
            _login = value;
        }
        public function get login():String {
            return _login;
        }

        public function set senha(value:String):void {
            _senha = value;
        }
        public function get senha():String {
            return _senha;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _login = input.readObject() as String;
            _senha = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_login);
            output.writeObject(_senha);
        }
    }
}