/**
 * Generated by Gas3 v3.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package Forms {

    [Bindable]
    [RemoteClass(alias="Forms.Cad_Itens")]
    public class Cad_Itens extends Cad_ItensBase {

        public function Cad_Itens() {
            super();
        }
    }
}